# Generated by Django 5.0.4 on 2024-04-12 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_rename_title_book_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
    ]
