# Generated by Django 5.0.4 on 2024-04-12 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_rename_name_book_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='title',
            new_name='name',
        ),
    ]
